AgroPharm/Controllers/BuyController.cs
using AgroPharm.Interfaces;
using AgroPharm.Models.Request;
using AgroPharm.Models;
using AgroPharm.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Org.BouncyCastle.Asn1.Ocsp;
using AgroPharm.Models.Response;

namespace AgroPharm.Controllers
{
    public class BuyController : Controller
    {
        private readonly BuyProductRepo _buyProduct;
        private readonly ProductRepo _product;
        private readonly OrganizationRepo _organization;
        private readonly MarketRepository _marketRepository;
        private readonly CurrencyRepo _currencyRepo;

        public BuyController(BuyProductRepo buyProduct, ProductRepo product, OrganizationRepo organization, MarketRepository marketRepository, CurrencyRepo currencyRepo)
        {
            _buyProduct = buyProduct;
            _product = product;
            _organization = organization;
            _marketRepository = marketRepository;
            _currencyRepo = currencyRepo;
        }
        // GET: BuyController
        public ActionResult Index()
        {
            try
            {
                var buyProducts = _buyProduct.GetBuyProducts();
                return View(buyProducts);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }

        // GET: BuyController/Create
        public ActionResult Create()
        {
            var products = _product.GetProducts().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.ProductName
            }).ToList();

            var organizations = _organization.GetOrganizations().Select(o => new SelectListItem
            {
                Value = o.Id.ToString(),
                Text = o.OrganizationName
            }).ToList();

            
            var currency = Convert.ToDecimal(_currencyRepo.GetLastCurrency());

            Console.WriteLine($"Текущий курс доллара 1 usd = {currency}");

            var model = new ViewModel
            {
                Products = products,
                Organizations = organizations,
                CurrencyNow = currency,
                BuyProductRequest = new BuyProductRequest()
            };

            return View(model);
        }

        // POST: BuyController/Create
        [HttpPost]
        public ActionResult Create(ViewModel buyProduct)
        {
            try
            {
                if (buyProduct.BuyProductRequest.ProductNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                if (buyProduct.BuyProductRequest.OrganizationNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование организации не указано." });
                }
                if (buyProduct.BuyProductRequest.BuyProductPrice == 0 || buyProduct.BuyProductRequest.BuyProductPriceUSD == 0)
                {
                    return Json(new { success = false, message = "Цена товара не указана." });
                }
                if (buyProduct.BuyProductRequest.BuyProductObem == 0)
                {
                    return Json(new { success = false, message = "Количество товара не указано." });
                }
                // Сохранение данных в базу
                var buyProducts = new BuyProductRequest
                {
                    ProductNameID = buyProduct.BuyProductRequest.ProductNameID,
                    OrganizationNameID = buyProduct.BuyProductRequest.OrganizationNameID,
                    BuyProductPrice = buyProduct.BuyProductRequest.BuyProductPrice,
                    BuyProductPriceUSD = buyProduct.BuyProductRequest.BuyProductPriceUSD,
                    BuyProductObem = buyProduct.BuyProductRequest.BuyProductObem,
                    BuyProductSumPrice = buyProduct.BuyProductRequest.BuyProductSumPrice,
                    BuyProductSumPriceUSD = buyProduct.BuyProductRequest.BuyProductSumPriceUSD,
                    BuyProductDate = buyProduct.BuyProductRequest.BuyProductDate,
                    BuyComment = buyProduct.BuyProductRequest.BuyComment
                };
                var market = new MarketRequest
                {
                    ProductNameID = buyProduct.BuyProductRequest.ProductNameID,
                    obemProducts = buyProduct.BuyProductRequest.BuyProductObem
                };
                _buyProduct.Create(buyProducts);
                _marketRepository.IncomeProduct(market);
                return Json(new { success = true, message = "Товар успешно куплен!" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }

        // GET: BuyController/Edit/5
        public ActionResult Edit(int id)
        {
            var products = _product.GetProducts().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.ProductName
            }).ToList();

            var organizations = _organization.GetOrganizations().Select(o => new SelectListItem
            {
                Value = o.Id.ToString(),
                Text = o.OrganizationName
            }).ToList();
            var currency = Convert.ToDecimal(_currencyRepo.GetLastCurrency());

            var itemsRecord = _buyProduct.GetBuyProducts().FirstOrDefault(b => b.Id == id);
            ViewModel? model = null;

            if (itemsRecord != null)
            {
                model = new ViewModel
                {
                    Products = products,
                    Organizations = organizations,
                    BuyProductRequest = new BuyProductRequest()
                    {
                        Id = id,
                        ProductNameID = itemsRecord?.ProductNameID ?? 0,
                        OrganizationNameID = itemsRecord?.OrganizationNameID ?? 0,
                        BuyProductPrice = itemsRecord?.BuyProductPrice ?? 0,
                        BuyProductPriceUSD = itemsRecord?.BuyProductPriceUSD ?? 0,
                        BuyProductObem = itemsRecord?.BuyProductObem ?? 0,
                        BuyProductSumPrice = itemsRecord?.BuyProductSumPrice ?? 0,
                        BuyProductSumPriceUSD = itemsRecord?.BuyProductSumPriceUSD ?? 0,
                        BuyComment = itemsRecord?.BuyComment
                    },
                    BuyProductResponse = itemsRecord,
                    CurrencyNow = currency,
                    tempQuantity = itemsRecord.BuyProductObem
                };
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ViewModel buyProduct)
        {
            try
            {
                if (buyProduct.BuyProductRequest.ProductNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                if (buyProduct.BuyProductRequest.OrganizationNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование организации не указано." });
                }
                if (buyProduct.BuyProductRequest.BuyProductPrice == 0 || buyProduct.BuyProductRequest.BuyProductPriceUSD == 0)
                {
                    return Json(new { success = false, message = "Цена товара не указана." });
                }
                if (buyProduct.BuyProductRequest.BuyProductObem == 0)
                {
                    return Json(new { success = false, message = "Количество товара не указано." });
                }
                var producrMarket = _marketRepository.GetMarketList().FirstOrDefault(p => p.ProductNameID == buyProduct.BuyProductRequest.ProductNameID);
                if (buyProduct.tempQuantity > buyProduct.BuyProductRequest.BuyProductObem)
                {
                    var market = new MarketRequest
                    {
                        ProductNameID = buyProduct.BuyProductRequest.ProductNameID,
                        obemProducts = buyProduct.tempQuantity - buyProduct.BuyProductRequest.BuyProductObem
                    };
                    var resMarket = _marketRepository.OutcomeProduct(market);
                    if(resMarket != "OK")
                    {
                        return Json(new { success = false, message = $"Произошла ошибка: {resMarket}" });
                    }
                    Console.WriteLine("От товара вычитана количество");
                }
                if (buyProduct.tempQuantity < buyProduct.BuyProductRequest.BuyProductObem)
                {
                    var market = new MarketRequest
                    {
                        ProductNameID = buyProduct.BuyProductRequest.ProductNameID,
                        obemProducts = buyProduct.BuyProductRequest.BuyProductObem - buyProduct.tempQuantity
                    };
                    _marketRepository.IncomeProduct(market);
                    Console.WriteLine("К товару прибалена количество");
                }

                var buyProducts = new BuyProductRequest
                {
                    Id = buyProduct.BuyProductRequest.Id,
                    ProductNameID = buyProduct.BuyProductRequest.ProductNameID,
                    OrganizationNameID = buyProduct.BuyProductRequest.OrganizationNameID,
                    BuyProductPrice = buyProduct.BuyProductRequest.BuyProductPrice,
                    BuyProductPriceUSD = buyProduct.BuyProductRequest.BuyProductPriceUSD,
                    BuyProductObem = buyProduct.BuyProductRequest.BuyProductObem,

AgroPharm/Controllers/CurrencyController.cs
using AgroPharm.Models;
using AgroPharm.Repositories;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace AgroPharm.Controllers
{
    public class CurrencyController : Controller
    {
        CurrencyRepo _currencyRepo;
        public CurrencyController(CurrencyRepo currencyRepo)
        {
            _currencyRepo = currencyRepo;
        }
        public IActionResult Index()
        {
            try
            {
                IEnumerable<Currency>? getCurrency = _currencyRepo.GetCurrencyList();
                var getCurrencyNow = Convert.ToDecimal(_currencyRepo.GetLastCurrency());
                var model = new ViewModel()
                {
                    Currency = getCurrency,
                    CurrencyNow = getCurrencyNow
                };
                return View(model);
            }
            catch(MySqlException mex)
            {
                throw;
            }
            catch (Exception)
            {
                throw;
            }
        }
        public ActionResult Edit()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Currency currency)
        {
            try
            {
                if (currency.USDtoTJS ==0)
                {
                    return Json(new { success = false, message = "Курс валют не указано" });
                }
                _currencyRepo.AddCurrency(currency);
                return Json(new { success = true, message = "Курс валют успешно обновлено!" });
               
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }
    }
}

AgroPharm/Controllers/ProductController.cs
using AgroPharm.Interfaces;
using AgroPharm.Models;
using AgroPharm.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Concurrent;

namespace AgroPharm.Controllers
{
    public class ProductController : Controller
    {
        private ProductRepo _porduct;
        public ProductController(ProductRepo product)
        {
            _porduct = product;
        }
        public IActionResult Index()
        {
            try
            {
                var result = _porduct.GetProducts();
                return View(result);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Ошибка: {ex.Message}" });
            }            
        }
        
        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                var product = _porduct.GetProducts().FirstOrDefault(p=>p.Id==id);
                if (product == null)
                {
                    return Json(new { success = false, message = "Наименование товара не найдена." });
                }
                _porduct.DeleteProduct(id);
                return Json(new { success = true, message = "Наименование товара успешно удалёна!" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Ошибка: {ex.Message}" });
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product product)
        {
            try
            {
                if (string.IsNullOrEmpty(product.ProductName))
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }

                bool checkName = _porduct.CheckProductName(product.ProductName);
                if (!checkName)
                {
                    _porduct.CreateProduct(product);
                    return Json(new { success = true, message = "Наименование товара успешно добавлено!" });
                }
                else
                {
                    return Json(new { success = false, message = "Наименование товара уже существует." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }

        public ActionResult Edit(int id) 
        {
            var result = _porduct.GetProducts().FirstOrDefault(p=>p.Id==id);

            return View("Edit", result);
        }

        [HttpPost]
        public ActionResult Edit(Product product) 
        {
            try
            {
                if (string.IsNullOrEmpty(product.ProductName))
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                var checkName = _porduct.CheckProductName(product.ProductName);                
                if (!checkName)
                {
                    _porduct.UpdateProduct(product);
                    return Json(new { success = true, message = "Наименование товара успешно изменено!" });
                }
                else
                {
                    return Json(new { success = false, message = "Наименование товара уже существует." });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }
    }
}

AgroPharm/Views/Shared/SuccessModal.cshtml
@model AgroPharm.Models.Request.MarketRequest

<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Заголовок модального окна</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>@Model.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <button type="button" class="btn btn-primary">Сохранить изменения</button>
            </div>
        </div>
    </div>
</div>

AgroPharm/Views/Shared/Warning.cshtml
<div class="page-content-wrapper">
	<div class="page-content" style="min-height:1539px">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="card card-box">
					<div class="card-head">
						<header>Внимание!</header>
					</div>
					<div class="card-body" id="bar-parent">						
						<div class="form-body">
							<div class="form-group row">
								<div class="content-center">
									<h3>Такое наименование уже существует!</h3>
								</div>
							</div>
							<div class="form-actions">
								<div class="row">
									<div class="offset-md-5 col-md-7">
										<a onclick="window.history.back();" class="btn btn-default">Понятно</a>
									</div>
								</div>
							</div>
						</div>						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

AgroPharm/Views/Shared/_ConfirmDeleteModal.cshtml
@section script{
    <script>
        
    </script>
}

AgroPharm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta name="description" content="Responsive Admin Pages" />
	

    <title>EskhataFarm | Market for ESG</title>
	
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet" type="text/css" />
    <!-- icons -->
	<link rel="stylesheet" type="text/css" href="@Url.Content("~/fonts/simple-line-icons/simple-line-icons.min.css")" />
    <link href="@Url.Content("~/fonts/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/fonts/material-design-icons/material-icon.css")" rel="stylesheet" type="text/css" />
    <!--bootstrap -->
	<link rel="stylesheet" href="@Url.Content("~/lib/bootstrap/dist/css/bootstrap.min.css")" />
    <link href="@Url.Content("~/assets/plugins/bootstrap/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/plugins/summernote/summernote.css")" rel="stylesheet">
	<link href="@Url.Content("~/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css")" rel="stylesheet" type="text/css" />
    <!-- Material Design Lite CSS -->
    <link rel="stylesheet" href="@Url.Content("~/assets/plugins/material/material.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/assets/css/material_style.css")">
    <!-- inbox style -->
    <link href="@Url.Content("~/assets/css/pages/inbox.min.css")" rel="stylesheet" type="text/css" />
    <!-- Theme S-->
    <link href="@Url.Content("~/assets/css/theme/light/theme_style.css")" rel="stylesheet" id="rt_style_components" type="text/css" />
    <link href="@Url.Content("~/assets/css/plugins.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/css/theme/light/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/css/responsive.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/assets/css/theme/light/theme-color.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/assets/css/pages/formlayout.css")" rel="stylesheet" type="text/css" />
    
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link href="@Url.Content("~/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.css")" rel="stylesheet" type="text/css">
	<link href="@Url.Content("~/lib/sweetalert2/dist/sweetalert2.css")" rel="stylesheet" type="text/css">

	<!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">-->

	

</head>
<br />
<br />
<body class="page-header-fixed sidemenu-closed-hidelogo page-content-white page-md header-white dark-sidebar-color logo-indigo" style="overflow-y: hidden;">
    <header>   
		<div class="page-wrapper">
			<!-- start header -->
			<div class="page-header navbar navbar-fixed-top">
				<div class="page-header-inner ">
					<!-- logo start -->
					<div class="page-logo">
                        <a asp-controller="Home" asp-action="Index">
							<span class="logo-default">AgroPharm</span>
						</a>
					</div>
					<!-- logo end -->
					<ul class="nav navbar-nav navbar-left in">
						<li><a href="#" class="menu-toggler sidebar-toggler"><i class="icon-menu"></i></a></li>
					</ul>
                    <form class="search-form-opened" asp-controller="Currency" asp-action="GetCurrensy" method="GET">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search..." name="query">
							<span class="input-group-btn">
								<a href="javascript:;" class="btn submit">
									<i class="icon-magnifier"></i>
								</a>
							</span>
						</div>
					</form>
					<!-- start mobile menu -->
					<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
						<span></span>
					</a>
					<!-- end mobile menu -->
					<!-- start header menu -->
					<div class="top-menu">
						<ul class="nav navbar-nav pull-right">
							<li><a><i class="fa fa-clock-o"></i><span id="DateLabel"></span>    <span id="TimeLabel" class="main-lbl"></span></a></li>
							<li><a href="javascript:;" class="fullscreen-btn"><i class="fa fa-arrows-alt"></i></a></li>	
						</ul>
					</div>
				</div>
			</div>
			
			<!-- end header -->
            <div class="sidebar-container">
                <div class="sidemenu-container navbar-collapse collapse fixed-menu" style="height: 100vh;">
                    <div id="remove-scroll">
                        <ul class="sidemenu page-header-fixed"
                            data-keep-expanded="false"
                            data-auto-scroll="true"
                            data-slide-speed="200"
                            style="padding-top: 20px;">
                            <li class="sidebar-toggler-wrapper hide">
                                <div class="sidebar-toggler">
                                    <span></span>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Home" asp-action="Dashboard" class="nav-link nav-toggle">
                                    <i class="material-icons">dashboard</i>
                                    <span class="title">Dashboard</span>
                                    <span class="selected"></span>
                                    <span class="arrow"></span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link nav-toggle">
                                    <i class="fa fa-plus"></i>
                                    <span class="title">Добавить</span><span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item">
                                        <a asp-controller="Product" asp-action="Index" class="nav-link">
                                            <i class="material-icons">library_add</i>
                                            <span class="title">Наименование товара</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Organization" asp-action="Index" class="nav-link">
                                            <i class="material-icons">location_city</i>
                                            <span class="title">Наименование организации</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="Customer" asp-action="Index" class="nav-link">
                                            <i class="material-icons">person_add</i>
                                            <span class="title">Наименование покупателя</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link nav-toggle" asp-controller="Buy" asp-action="Index">
                                    <i class="fa fa-shopping-cart"></i>
                                    <span class="title">Закупка</span><span class="arrow"></span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Sell" asp-action="Index" class="nav-link nav-toggle">
                                    <i class="material-icons">shopping_cart</i>
                                    <span class="title">Продажа</span><span class="arrow"></span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link nav-toggle">
                                    <i class="fa fa-reply"></i>
                                    <span class="title">Возврат</span><span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item">
                                        <a asp-controller="ReturnIn" asp-action="Index" class="nav-link">
                                            <i class="icon-user"></i>
                                            <span class="title">От пакупателя</span>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="ReturnOut" asp-action="Index" class="nav-link">
                                            <i class="material-icons">location_city</i>
                                            <span class="title">Организацию</span>
                                        </a>
                                    </li>                                    
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Currency" asp-action="Index" class="nav-link nav-toggle">
                                    <i class="fa fa-dollar"></i>
                                    <span class="title">Курс валют</span><span class="arrow"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container-fluid" style="margin-top: 20px;">
            @RenderBody()

    </div>
	

    @await RenderSectionAsync("Scripts", required: false)


	<script src="@Url.Content("~/assets/plugins/jquery/jquery.min.js")"></script>
	<script src="@Url.Content("~/assets/plugins/popper/popper.js")"></script>
	<script src="@Url.Content("~/assets/plugins/jquery-blockui/jquery.blockui.min.js")"></script>
	<script src="@Url.Content("~/assets/plugins/jquery-slimscroll/jquery.slimscroll.js")"></script>
    <!-- bootstra-->
	<script src="@Url.Content("~/assets/plugins/bootstrap/js/bootstrap.min.js")"></script>
	<script src="@Url.Content("~/assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js")"></script>
	<script src="@Url.Content("~/assets/plugins/sparkline/jquery.sparkline.js")"></script>
	<script src="@Url.Content("~/assets/js/pages/sparkline/sparkline-data.js")"></script>
    <!-- Common j-->
	<script src="@Url.Content("~/assets/js/app.js")"></script>
	<script src="@Url.Content("~/assets/js/layout.js")"></script>
	<script src="@Url.Content("~/assets/js/theme-color.js")"></script>
    <!-- material-->
	<script src="@Url.Content("~/assets/plugins/material/material.min.js")"></script>
    
    <!-- summerno-->
    <script src="@Url.Content("~/assets/plugins/summernote/summernote.js")"></script>
    <script src="@Url.Content("~/assets/js/pages/summernote/summernote-data.js")"></script>

	<script src="@Url.Content("~/assets/plugins/datatables/jquery.dataTables.min.js")"></script>
	<script src="@Url.Content("~/assets/plugins/datatables/plugins/bootstrap/dataTables.bootstrap4.min.js")"></script>
	<script src="@Url.Content("~/assets/js/pages/table/table_data.js")"></script>

	<script src="@Url.Content("~/lib/bootstrap/dist/js/bootstrap.bundle.min.js")"></script>
	<script src="@Url.Content("~/lib/sweetalert2/dist/sweetalert2.js")"></script>

	<script src="@Url.Content("~/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js")" charset="UTF-8"></script>
	<script src="@Url.Content("~/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker-init.js")" charset="UTF-8"></script>

    <script src="@Url.Content("~/assets/js/pages/extra-pages/pages.js")"></script>

    
	
	<script>
			if (document.getElementById) onload = function () {
			setInterval(function() {
				var dt = new Date();
				document.getElementById('DateLabel').innerText = +("0" + dt.getDate()).slice(-2) + "/" + ("0" + (dt.getMonth() + 1)).slice(-2) + "/" + dt.getFullYear();
				document.getElementById('TimeLabel').innerText = +("0" + dt.getHours()).slice(-2) + ":" + ("0" + dt.getMinutes()).slice(-2) + ":" + ("0" + dt.getSeconds()).slice(-2);
			}, 50);
		}
	</script>   

</body>
</html>