AgroPharm/Controllers/ReturnOutController.cs
using AgroPharm.Interfaces;
using AgroPharm.Models.Request;
using AgroPharm.Models;
using AgroPharm.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MySql.Data.MySqlClient;

namespace AgroPharm.Controllers
{
    public class ReturnOutController : Controller
    {
        private readonly ReturnOutRepo _returnOut;
        private readonly ProductRepo _product;
        private readonly OrganizationRepo _organization;
        private readonly MarketRepository _marketRepository;

        public ReturnOutController(ReturnOutRepo returnOut, ProductRepo product, OrganizationRepo organization, MarketRepository marketRepository)
        {
            _returnOut = returnOut;
            _product = product;
            _organization = organization;
            _marketRepository = marketRepository;
        }
        public IActionResult Index()
        {
            try
            {
                return View(_returnOut.GetReturnOutProducts());
            }
            catch (MySqlException me)
            {
                return RedirectToAction("/Home/ServerError");
            }
            catch (Exception)
            {
                throw;
            }
            
        }
        public ActionResult Create()
        {
            var products = _product.GetProducts().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.ProductName
            }).ToList();

            var organizations = _organization.GetOrganizations().Select(o => new SelectListItem
            {
                Value = o.Id.ToString(),
                Text = o.OrganizationName
            }).ToList();

            var model = new ViewModel
            {
                Products = products,
                Organizations = organizations,
                ReturnOutRequest = new ReturnOutRequest()
            };

            return View(model);
        }

        // POST: BuyController/Create
        [HttpPost]
        public ActionResult Create(ViewModel returnOutProduct)
        {
            try
            {
                if (returnOutProduct.ReturnOutRequest.ProductNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                if (returnOutProduct.ReturnOutRequest.OrganizationNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование организации не указано." });
                }
                if (returnOutProduct.ReturnOutRequest.ReturnOutProductPriceUSD == 0 || returnOutProduct.ReturnOutRequest.ReturnOutProductPrice == 0)
                {
                    return Json(new { success = false, message = "Цена товара не указана." });
                }
                if (returnOutProduct.ReturnOutRequest.ReturnOutProductObem == 0)
                {
                    return Json(new { success = false, message = "Количество товара не указано." });
                }
                // Сохранение данных в базу
                var returnOutProducts = new ReturnOutRequest
                {
                    ProductNameID = returnOutProduct.ReturnOutRequest.ProductNameID,
                    OrganizationNameID = returnOutProduct.ReturnOutRequest.OrganizationNameID,
                    ReturnOutProductPrice = returnOutProduct.ReturnOutRequest.ReturnOutProductPrice,
                    ReturnOutProductPriceUSD = returnOutProduct.ReturnOutRequest.ReturnOutProductPriceUSD,
                    ReturnOutProductObem = returnOutProduct.ReturnOutRequest.ReturnOutProductObem,
                    ReturnOutProductSumPrice = returnOutProduct.ReturnOutRequest.ReturnOutProductSumPrice,
                    ReturnOutProductSumPriceUSD = returnOutProduct.ReturnOutRequest.ReturnOutProductSumPriceUSD,
                    ReturnOutProductDate = returnOutProduct.ReturnOutRequest.ReturnOutProductDate,
                    ReturnOutComment = returnOutProduct.ReturnOutRequest.ReturnOutComment
                };
                var market = new MarketRequest
                {
                    ProductNameID = returnOutProduct.ReturnOutRequest.ProductNameID,
                    obemProducts = returnOutProduct.ReturnOutRequest.ReturnOutProductObem
                };

                var resMarket = _marketRepository.OutcomeProduct(market);
                if (resMarket == "OK")
                {
                    _returnOut.Create(returnOutProducts);
                    return Json(new { success = true, message = "Товар успешно возврашён!" });
                }
                else
                {
                    return Json(new { warning = true, message = resMarket });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }

        // GET: BuyController/Edit/5
        public ActionResult Edit(int id)
        {
            var products = _product.GetProducts().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.ProductName
            }).ToList();

            var organizations = _organization.GetOrganizations().Select(o => new SelectListItem
            {
                Value = o.Id.ToString(),
                Text = o.OrganizationName
            }).ToList();

            var itemsRecord = _returnOut.GetReturnOutProducts().FirstOrDefault(b => b.Id == id);
            ViewModel? model = null;

            if (itemsRecord != null)
            {
                model = new ViewModel
                {
                    Products = products,
                    Organizations = organizations,
                    ReturnOutRequest = new ReturnOutRequest()
                    {
                        Id = id,
                        ProductNameID = itemsRecord?.ProductNameID ?? 0,
                        OrganizationNameID = itemsRecord?.OrganizationNameID ?? 0,
                        ReturnOutProductPrice = itemsRecord?.ReturnOutProductPrice ?? 0,
                        ReturnOutProductPriceUSD = itemsRecord?.ReturnOutProductPriceUSD ?? 0,
                        ReturnOutProductObem = itemsRecord?.ReturnOutProductObem ?? 0,
                        ReturnOutProductSumPrice = itemsRecord?.ReturnOutSumProductPrice ?? 0,
                        ReturnOutProductSumPriceUSD = itemsRecord?.ReturnOutSumProductPriceUSD ?? 0,
                        ReturnOutComment = itemsRecord?.ReturnOutComment
                    },
                    ReturnOutResponse = itemsRecord,

                    tempQuantity = itemsRecord.ReturnOutProductObem
                };
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ViewModel ReturnOutProduct)
        {
            try
            {
                if (ReturnOutProduct.ReturnOutRequest.ProductNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                if (ReturnOutProduct.ReturnOutRequest.OrganizationNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование организации не указано." });
                }
                if (ReturnOutProduct.ReturnOutRequest.ReturnOutProductPrice == 0 || ReturnOutProduct.ReturnOutRequest.ReturnOutProductPriceUSD == 0)
                {
                    return Json(new { success = false, message = "Цена товара не указана." });
                }
                if (ReturnOutProduct.ReturnOutRequest.ReturnOutProductObem == 0)
                {
                    return Json(new { success = false, message = "Количество товара не указано." });
                }
                var producrMarket = _marketRepository.GetMarketList().FirstOrDefault(p => p.ProductNameID == ReturnOutProduct.ReturnOutRequest.ProductNameID);
                if (ReturnOutProduct.tempQuantity > ReturnOutProduct.ReturnOutRequest.ReturnOutProductObem)
                {
                    var market = new MarketRequest
                    {
                        ProductNameID = ReturnOutProduct.ReturnOutRequest.ProductNameID,
                        obemProducts = ReturnOutProduct.tempQuantity - ReturnOutProduct.ReturnOutRequest.ReturnOutProductObem
                    };
                    _marketRepository.IncomeProduct(market);
                }
                if (ReturnOutProduct.tempQuantity < ReturnOutProduct.ReturnOutRequest.ReturnOutProductObem)
                {
                    var market = new MarketRequest
                    {
                        ProductNameID = ReturnOutProduct.ReturnOutRequest.ProductNameID,
                        obemProducts = ReturnOutProduct.ReturnOutRequest.ReturnOutProductObem - ReturnOutProduct.tempQuantity
                    };
                    var resMarket = _marketRepository.OutcomeProduct(market);
                    if (resMarket != "OK")
                    {
                        return Json(new { success = false, message = $"Произошла ошибка: {resMarket}" });
                    }
                }

                var sellProducts = new ReturnOutRequest
                {
                    Id = ReturnOutProduct.ReturnOutRequest.Id,
                    ProductNameID = ReturnOutProduct.ReturnOutRequest.ProductNameID,
                    OrganizationNameID = ReturnOutProduct.ReturnOutRequest.OrganizationNameID,
                    ReturnOutProductPriceUSD = ReturnOutProduct.ReturnOutRequest.ReturnOutProductPrice,
                    ReturnOutProductPrice = ReturnOutProduct.ReturnOutRequest.ReturnOutProductPriceUSD,
                    ReturnOutProductObem = ReturnOutProduct.ReturnOutRequest.ReturnOutProductObem,

AgroPharm/Views/ReturnOut/Create.cshtml
@model AgroPharm.Models.ViewModel

<div class="page-content-wrapper">
	<div class="page-content">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="card">
					<div class="card-head">
						<header>Возврат товара организацию</header>
					</div>
					<div class="card-body" id="bar-parent">

						<form id="createProductForm" asp-controller="ReturnOut" asp-action="Create" class="form-horizontal" method="post">
							<div class="form-body">
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименование товара <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="ReturnOutRequest.ProductNameID" asp-items="Model.Products" required>
											<option value="">Выберите...</option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименовании организации <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="ReturnOutRequest.OrganizationNameID" asp-items="Model.Organizations" required>
											<option value="">Выберите...</option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceTJS" asp-for="ReturnOutRequest.ReturnOutProductPrice" placeholder="Введите цену товара TJS" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceUSD" asp-for="ReturnOutRequest.ReturnOutProductPriceUSD" placeholder="Введите цену товара в USD" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Количество товара
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="quantity" asp-for="ReturnOutRequest.ReturnOutProductObem" placeholder="Введите количество" class="form-control input-height" min="1" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumTJS" asp-for="ReturnOutRequest.ReturnOutProductSumPrice" placeholder="Сумма TJS" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumUSD" asp-for="ReturnOutRequest.ReturnOutProductSumPriceUSD" placeholder="Сумма USD" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Комментарий
									</label>
									<div class="col-md-5">
										<textarea asp-for="ReturnOutRequest.ReturnOutComment" placeholder="Коментарии к товару" class="form-control-textarea" rows="5"></textarea>
									</div>
								</div>
								<input type="hidden" name="__RequestVerificationToken" value="@Html.AntiForgeryToken()" />
								<div class="form-actions">
									<div class="row">
										<div class="offset-md-3 col-md-9">
											<button asp-controller="ReturnOut" asp-action="Create" class="btn btn-primary">Продать</button>
											<button type="button" class="btn btn-default" onclick="window.history.back();">Отмена</button>
										</div>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>
<script src="@Url.Content("~/js/сalculatePrice.js")"></script>
<script src="@Url.Content("~/js/createResponse.js")"></script>

AgroPharm/Views/ReturnOut/Edit.cshtml
@model AgroPharm.Models.ViewModel
@{
	double? oldQuantity = Model.tempQuantity;
}
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="card">
					<div class="card-head">
						<header>Редактирование возврата организацию</header>
					</div>
					<div class="card-body" id="bar-parent">
						<form id="editProductForm" asp-controller="ReturnOut" asp-action="Edit" class="form-horizontal" method="post">
							<div class="form-body">
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименование товара <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="ReturnOutRequest.ProductNameID" asp-items="Model.Products" required>
											<option value="Response.ProductName"></option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименовании организации <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="ReturnOutRequest.OrganizationNameID" asp-items="Model.Organizations" required>
											<option value="Response.OrganizationName"></option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceTJS" asp-for="ReturnOutRequest.ReturnOutProductPrice" placeholder="Введите цену товара TJS" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceUSD" asp-for="ReturnOutRequest.ReturnOutProductPriceUSD" placeholder="Введите цену товара в USD" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Количество товара
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="quantity" asp-for="ReturnOutRequest.ReturnOutProductObem" placeholder="Введите количество" class="form-control input-height" min="1" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumTJS" asp-for="ReturnOutRequest.ReturnOutProductSumPrice" placeholder="Сумма TJS" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumUSD" asp-for="ReturnOutRequest.ReturnOutProductSumPriceUSD" placeholder="Сумма USD" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Комментарий
									</label>
									<div class="col-md-5">
										<textarea asp-for="ReturnOutRequest.ReturnOutComment" placeholder="Коментарий к товару" class="form-control-textarea" rows="5"></textarea>
									</div>
								</div>
								<input type="hidden" asp-for="tempQuantity">
								<input type="hidden" asp-for="ReturnOutRequest.Id">
								<input type="hidden" name="__RequestVerificationToken" value="@Html.AntiForgeryToken()" />
								<div class="form-actions">
									<div class="row">
										<div class="offset-md-3 col-md-9">
											<button asp-controller="ReturnOut" asp-action="Edit" class="btn btn-primary">Сохранить изменения</button>
											<button type="button" class="btn btn-default" onclick="window.history.back();">Отмена</button>
										</div>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="@Url.Content("~/js/editRecord.js")"></script>
<script src="@Url.Content("~/js/сalculatePrice.js")"></script>

AgroPharm/Views/ReturnOut/Index.cshtml
@model IEnumerable<AgroPharm.Models.Response.ReturnOutResponse>

@{
    int count = 1;
    ViewData["Title"] = "BuyProduct Page";
}

<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-head">
                                            <header>Возвраты организацию</header>
                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                                <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                                                <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-6 col-6">
                                                    <div class="btn-group">
                                                        <a asp-controller="ReturnOut" asp-action="Create" id="addRow" class="btn btn-info">
                                                            Возврат <i class="fa fa-plus"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-sm-6 col-6">
                                                    <div class="btn-group pull-right">
                                                        <a class="btn deepPink-bgcolor  btn-outline dropdown-toggle" data-toggle="dropdown">
                                                            Инструменты
                                                            <i class="fa fa-angle-down"></i>
                                                        </a>
                                                        <ul class="dropdown-menu pull-right">
                                                            <li>
                                                                <a asp-controller="Home" asp-action="PrintReport">
                                                                    <i class="fa fa-print"></i> Print
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a asp-controller="Home" asp-action="PrintReport">
                                                                    <i class="fa fa-file-pdf-o"></i> Save as PDF
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a href="javascript:;">
                                                                    <i class="fa fa-file-excel-o"></i> Export to Excel
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column valign-middle" id="example4">
                                                    <thead>
                                                        <tr>
                                                            <th scope="col" class="text-center">№</th>
                                                            <th scope="col" class="text-center">ID товара</th>
                                                            <th scope="col" class="text-center">Наименование продукта</th>
                                                            <th scope="col" class="text-center">Название организации</th>
                                                            <th scope="col" class="text-center">Цена за единицу (TJS)</th>
                                                            <th scope="col" class="text-center">Цена за единицу ($)</th>
                                                            <th scope="col" class="text-center">Количество</th>
                                                            <th scope="col" class="text-center">Общая сумма (TJS)</th>
                                                            <th scope="col" class="text-center">Общая сумма ($)</th>
                                                            <th scope="col" class="text-center">Дата покупки</th>
                                                            <th scope="col" class="text-center">Комментарий</th>
                                                            <th scope="col" class="text-center">Действия</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td class="text-center">@count</td>
                                                                <td class="text-center">@item.Id</td>
                                                                <td class="text-center">@item.ProductName</td>
                                                                <td class="text-center">@item.OrganizationName</td>
                                                                <td class="text-center">@item.ReturnOutProductPrice?.ToString("N2")</td>
                                                                <td class="text-center">@item.ReturnOutProductPriceUSD?.ToString("N2")</td>
                                                                <td class="text-center">@item.ReturnOutProductObem?.ToString("N2")</td>
                                                                <td class="text-center">@item.ReturnOutSumProductPrice?.ToString("N2")</td>
                                                                <td class="text-center">@item.ReturnOutSumProductPriceUSD?.ToString("N2")</td>
                                                                <td class="text-center">@item.ReturnOutProductDate?.ToString("dd.MM.yyyy")</td>
                                                                <td class="text-center">@item.ReturnOutComment</td>
                                                                <td class="text-center">
                                                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-xs">
                                                                        <i class="fa fa-pencil"></i>
                                                                    </a>
                                                                    <a onclick='deleteItem(@Html.Raw(Json.Serialize(item)))' class="btn btn-danger btn-xs" title="Удалить">
                                                                        <i class="fa fa-trash-o "></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            count++;
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="@Url.Content("~/js/deleteRecord.js")"></script>