AgroPharm/Controllers/SellController.cs
using AgroPharm.Interfaces;
using AgroPharm.Models.Request;
using AgroPharm.Models;
using AgroPharm.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AgroPharm.Controllers
{
    public class SellController : Controller
    {
        private readonly SellProductRepo _sellProduct;
        private readonly ProductRepo _product;
        private readonly CustomerRepo _customer;
        private readonly MarketRepository _marketRepository;
        public SellController(SellProductRepo sellProduct, ProductRepo product, CustomerRepo customer, MarketRepository marketRepository)
        {
            _sellProduct = sellProduct;
            _product = product;
            _customer = customer;
            _marketRepository = marketRepository;
        }
        public IActionResult Index()
        {
            try
            {
                return View(_sellProduct.GetSellProducts());
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }

        public ActionResult Create()
        {
            var products = _product.GetProducts().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.ProductName
            }).ToList();

            var customers = _customer.GetCustomers().Select(o => new SelectListItem
            {
                Value = o.Id.ToString(),
                Text = o.customerName
            }).ToList();

            var model = new ViewModel
            {
                Products = products,
                Customers = customers,
                SellRequest = new SellProductRequest()
            };

            return View(model);
        }

        // POST: BuyController/Create
        [HttpPost]
        public ActionResult Create(ViewModel sellProduct)
        {
            try
            {
                if (sellProduct.SellRequest.ProductNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                if (sellProduct.SellRequest.CustomerNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование организации не указано." });
                }
                if (sellProduct.SellRequest.SellProductPrice == 0 || sellProduct.SellRequest.SellProductPrice == 0)
                {
                    return Json(new { success = false, message = "Цена товара не указана." });
                }
                if (sellProduct.SellRequest.SellProductPrice == 0)
                {
                    return Json(new { success = false, message = "Количество товара не указано." });
                }
                // Сохранение данных в базу
                var sellProducts = new SellProductRequest
                {
                    ProductNameID = sellProduct.SellRequest.ProductNameID,
                    CustomerNameID = sellProduct.SellRequest.CustomerNameID,
                    SellProductPrice = sellProduct.SellRequest.SellProductPrice,
                    SellProductPriceUSD = sellProduct.SellRequest.SellProductPriceUSD,
                    SellProductObem = sellProduct.SellRequest.SellProductObem,
                    SellProductSumPrice = sellProduct.SellRequest.SellProductSumPrice,
                    SellProductSumPriceUSD = sellProduct.SellRequest.SellProductSumPriceUSD,
                    SellProductDate = sellProduct.SellRequest.SellProductDate,
                    SellComment = sellProduct.SellRequest.SellComment
                };
                var market = new MarketRequest
                {
                    ProductNameID = sellProduct.SellRequest.ProductNameID,
                    obemProducts = sellProduct.SellRequest.SellProductObem
                };
                
                var resMarket = _marketRepository.OutcomeProduct(market);
                if (resMarket == "OK")
                {
                    _sellProduct.Create(sellProducts);
                    return Json(new { success = true, message = "Товар успешно продан!" });
                }
                else
                {
                    return Json(new { warning = true, message = resMarket });
                }
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }

        // GET: BuyController/Edit/5
        public ActionResult Edit(int id)
        {
            var products = _product.GetProducts().Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.ProductName
            }).ToList();

            var organizations = _customer.GetCustomers().Select(o => new SelectListItem
            {
                Value = o.Id.ToString(),
                Text = o.customerName
            }).ToList();

            var itemsRecord = _sellProduct.GetSellProducts().FirstOrDefault(b => b.Id == id);
            ViewModel? model = null;

            if (itemsRecord != null)
            {
                model = new ViewModel
                {
                    Products = products,
                    Organizations = organizations,
                    SellRequest = new SellProductRequest(){
                        Id = id,
                        ProductNameID = itemsRecord?.ProductNameID ?? 0,
                        CustomerNameID = itemsRecord?.CustomerNameID ?? 0,
                        SellProductPrice = itemsRecord?.SellProductPrice ?? 0,
                        SellProductPriceUSD = itemsRecord?.SellProductPriceUSD ?? 0,
                        SellProductObem = itemsRecord?.SellProductObem ?? 0,
                        SellProductSumPrice = itemsRecord?.SellProductSumPrice ?? 0,
                        SellProductSumPriceUSD = itemsRecord?.SellProductSumPriceUSD ?? 0,
                        SellComment = itemsRecord?.SellComment
                    },
                    SellResponse = itemsRecord,

                    tempQuantity = itemsRecord.SellProductObem
                };
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(ViewModel sellProduct)
        {
            try
            {
                if (sellProduct.SellRequest.ProductNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование товара не указано." });
                }
                if (sellProduct.SellRequest.CustomerNameID == 0)
                {
                    return Json(new { success = false, message = "Наименование организации не указано." });
                }
                if (sellProduct.SellRequest.SellProductPrice == 0 || sellProduct.SellRequest.SellProductPriceUSD == 0)
                {
                    return Json(new { success = false, message = "Цена товара не указана." });
                }
                if (sellProduct.SellRequest.SellProductObem == 0)
                {
                    return Json(new { success = false, message = "Количество товара не указано." });
                }
                var producrMarket = _marketRepository.GetMarketList().FirstOrDefault(p => p.ProductNameID == sellProduct.SellRequest.ProductNameID);
                if (sellProduct.tempQuantity > sellProduct.SellRequest.SellProductObem)
                {
                    var market = new MarketRequest
                    {
                        ProductNameID = sellProduct.SellRequest.ProductNameID,
                        obemProducts = sellProduct.tempQuantity - sellProduct.SellRequest.SellProductObem
                    };
                    _marketRepository.IncomeProduct(market);
                }
                if (sellProduct.tempQuantity < sellProduct.SellRequest.SellProductObem)
                {
                    var market = new MarketRequest
                    {
                        ProductNameID = sellProduct.SellRequest.ProductNameID,
                        obemProducts = sellProduct.SellRequest.SellProductObem - sellProduct.tempQuantity
                    };
                    var resMarket = _marketRepository.OutcomeProduct(market);
                    if (resMarket != "OK")
                    {
                        return Json(new { success = false, message = $"Произошла ошибка: {resMarket}" });
                    }
                    
                }

                var sellProducts = new SellProductRequest
                {
                    Id = sellProduct.SellRequest.Id,
                    ProductNameID = sellProduct.SellRequest.ProductNameID,
                    CustomerNameID = sellProduct.SellRequest.CustomerNameID,
                    SellProductPriceUSD = sellProduct.SellRequest.SellProductPriceUSD,
                    SellProductPrice = sellProduct.SellRequest.SellProductPrice,
                    SellProductObem = sellProduct.SellRequest.SellProductObem,
                    SellProductSumPrice = sellProduct.SellRequest.SellProductSumPrice,
                    SellProductSumPriceUSD = sellProduct.SellRequest.SellProductSumPriceUSD,
                    SellProductDate = sellProduct.SellRequest.SellProductDate,
                    SellComment = sellProduct.SellRequest.SellComment
                };
                _sellProduct.Edit(sellProducts);
                return Json(new { success = true, message = "Продажа успешно изменена!" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = $"Произошла ошибка: {ex.Message}" });
            }
        }


        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {

AgroPharm/Views/Sell/Create.cshtml
@model AgroPharm.Models.ViewModel

<div class="page-content-wrapper">
	<div class="page-content">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="card">
					<div class="card-head">
						<header>Продажа товара</header>
					</div>
					<div class="card-body" id="bar-parent">

						<form id="createProductForm" asp-controller="Sell" asp-action="Create" class="form-horizontal" method="post">
							<div class="form-body">
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименование товара <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="SellRequest.ProductNameID" asp-items="Model.Products" required>
											<option value="">Выберите...</option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименовании организации <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="SellRequest.CustomerNameID" asp-items="Model.Customers" required>
											<option value="">Выберите...</option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceTJS" asp-for="SellRequest.SellProductPrice" placeholder="Введите цену товара TJS" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceUSD" asp-for="SellRequest.SellProductPriceUSD" placeholder="Введите цену товара в USD" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Количество товара
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="quantity" asp-for="SellRequest.SellProductObem" placeholder="Введите количество" class="form-control input-height" min="1" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumTJS" asp-for="SellRequest.SellProductSumPrice" placeholder="Сумма TJS" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumUSD" asp-for="SellRequest.SellProductSumPriceUSD" placeholder="Сумма USD" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Комментарий
									</label>
									<div class="col-md-5">
										<textarea asp-for="SellRequest.SellComment" placeholder="Коментарии к товару" class="form-control-textarea" rows="5"></textarea>
									</div>
								</div>
								<input type="hidden" name="__RequestVerificationToken" value="@Html.AntiForgeryToken()" />
								<div class="form-actions">
									<div class="row">
										<div class="offset-md-3 col-md-9">
											<button asp-controller="Sell" asp-action="Create" class="btn btn-primary">Продать</button>
											<button type="button" class="btn btn-default" onclick="window.history.back();">Отмена</button>
										</div>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>
<script src="@Url.Content("~/js/сalculatePrice.js")"></script>
<script src="@Url.Content("~/js/createResponse.js")"></script>

AgroPharm/Views/Sell/Edit.cshtml
@model AgroPharm.Models.ViewModel
@{
	double? oldQuantity = Model.tempQuantity;
}
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="row">
			<div class="col-md-12 col-sm-12">
				<div class="card">
					<div class="card-head">
						<header>Редактирование проданного товара</header>
					</div>
					<div class="card-body" id="bar-parent">
						<form id="editProductForm" asp-controller="Sell" asp-action="Edit" class="form-horizontal" method="post">
							<div class="form-body">
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименование товара <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="SellRequest.ProductNameID" asp-items="Model.Products" required>
											<option value="Response.ProductName"></option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Наименовании покупателя <span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<select class="form-control input-height" asp-for="SellRequest.CustomerNameID" asp-items="Model.Organizations" required>
											<option value="Response."></option>
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceTJS" asp-for="SellRequest.SellProductPrice" placeholder="Введите цену товара TJS" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Цена (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="priceUSD" asp-for="SellRequest.SellProductPriceUSD" placeholder="Введите цену товара в USD" class="form-control input-height" step="0.01" min="0.01" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Количество товара
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="quantity" asp-for="SellRequest.SellProductObem" placeholder="Введите количество" class="form-control input-height" min="1" required />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (TJS)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumTJS" asp-for="SellRequest.SellProductSumPrice" placeholder="Сумма TJS" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Сумма (USD)
										<span class="required"> * </span>
									</label>
									<div class="col-md-5">
										<input type="number" id="sumUSD" asp-for="SellRequest.SellProductSumPriceUSD" placeholder="Сумма USD" class="form-control input-height" readonly />
									</div>
								</div>
								<div class="form-group row">
									<label class="control-label col-md-3">
										Комментарий
									</label>
									<div class="col-md-5">
										<textarea asp-for="SellRequest.SellComment" placeholder="Коментарий к товару" class="form-control-textarea" rows="5"></textarea>
									</div>
								</div>
								<input type="hidden" asp-for="tempQuantity">
								<input type="hidden" asp-for="SellRequest.Id">
								<input type="hidden" name="__RequestVerificationToken" value="@Html.AntiForgeryToken()" />
								<div class="form-actions">
									<div class="row">
										<div class="offset-md-3 col-md-9">
											<button asp-controller="Sell" asp-action="Edit" class="btn btn-primary">Сохранить изменения</button>
											<button type="button" class="btn btn-default" onclick="window.history.back();">Отмена</button>
										</div>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="@Url.Content("~/js/editRecord.js")"></script>
<script src="@Url.Content("~/js/сalculatePrice.js")"></script>

AgroPharm/Views/Sell/Index.cshtml
@model IEnumerable<AgroPharm.Models.Response.SellProductResponse>
@{
    int count = 1;
    ViewData["Title"] = "SellProduct Page";
}

<div class="page-content-wrapper">
    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <div class="tabbable-line">
                    <div class="tab-content">
                        <div class="tab-pane active fontawesome-demo" id="tab1">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-head">
                                            <header>Все проданные товары</header>
                                            <div class="tools">
                                                <a class="fa fa-repeat btn-color box-refresh" href="javascript:;"></a>
                                                <a class="t-collapse btn-color fa fa-chevron-down" href="javascript:;"></a>
                                                <a class="t-close btn-color fa fa-times" href="javascript:;"></a>
                                            </div>
                                        </div>
                                        <div class="card-body ">
                                            <div class="row">
                                                <div class="col-md-6 col-sm-6 col-6">
                                                    <div class="btn-group">
                                                        <a asp-controller="Sell" asp-action="Create" id="addRow" class="btn btn-info">
                                                            Продать <i class="fa fa-plus"></i>
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="col-md-6 col-sm-6 col-6">
                                                    <div class="btn-group pull-right">
                                                        <a class="btn deepPink-bgcolor  btn-outline dropdown-toggle" data-toggle="dropdown">
                                                            Инструменты
                                                            <i class="fa fa-angle-down"></i>
                                                        </a>
                                                        <ul class="dropdown-menu pull-right">
                                                            <li>
                                                                <a asp-controller="Home" asp-action="PrintReport">
                                                                    <i class="fa fa-print"></i> Print
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a asp-controller="Home" asp-action="PrintReport">
                                                                    <i class="fa fa-file-pdf-o"></i> Save as PDF
                                                                </a>
                                                            </li>
                                                            <li>
                                                                <a href="javascript:;">
                                                                    <i class="fa fa-file-excel-o"></i> Export to Excel
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="table-scrollable">
                                                <table class="table table-striped table-bordered table-hover table-checkable order-column valign-middle" id="example4">
                                                    <thead>
                                                        <tr>
                                                            <th scope="col" class="text-center">№</th>
                                                            <th scope="col" class="text-center">ID товара</th>
                                                            <th scope="col" class="text-center">Наименование продукта</th>
                                                            <th scope="col" class="text-center">Наименование покупателя</th>
                                                            <th scope="col" class="text-center">Цена за единицу (TJS)</th>
                                                            <th scope="col" class="text-center">Цена за единицу ($)</th>
                                                            <th scope="col" class="text-center">Количество</th>
                                                            <th scope="col" class="text-center">Общая сумма (TJS)</th>
                                                            <th scope="col" class="text-center">Общая сумма ($)</th>
                                                            <th scope="col" class="text-center">Дата продажи</th>
                                                            <th scope="col" class="text-center">Комментарий</th>
                                                            <th scope="col" class="text-center">Действия</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @foreach (var item in Model)
                                                        {
                                                            <tr class="odd gradeX">
                                                                <td class="text-center">@count</td>
                                                                <td class="text-center">@item.Id</td>
                                                                <td class="text-center">@item.ProductName</td>
                                                                <td class="text-center">@item.CustomerName</td>
                                                                <td class="text-center">@item.SellProductSumPrice?.ToString("N2")</td>
                                                                <td class="text-center">@item.SellProductPriceUSD?.ToString("N2")</td>
                                                                <td class="text-center">@item.SellProductObem?.ToString("N2")</td>
                                                                <td class="text-center">@item.SellProductSumPrice?.ToString("N2")</td>
                                                                <td class="text-center">@item.SellProductSumPriceUSD?.ToString("N2")</td>
                                                                <td class="text-center">@item.SellProductDate?.ToString("dd.MM.yyyy")</td>
                                                                <td class="text-center">@item.SellComment</td>
                                                                <td class="text-center">
                                                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-xs">
                                                                        <i class="fa fa-pencil"></i>
                                                                    </a>
                                                                    <a onclick='deleteItem(@Html.Raw(Json.Serialize(item)))' class="btn btn-danger btn-xs" title="Удалить">
                                                                        <i class="fa fa-trash-o "></i>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            count++;
                                                        }
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="@Url.Content("~/js/deleteRecord.js")"></script>